### ISSUE TITLE
 jpegdecompresssurface : picture decode failed : e00002d1

### ISSUE THREAD

**Issue by totoourworld** [martinrybak/SQLClient#41] opened 2017-01-23 16:58 UTC
jpegdecompresssurface : picture decode failed : e00002d1
I can get exact same data as image data from sql server.
So i try to load image from NSData, below the code,

- (void)process:(NSArray*)results
{
    NSArray *table=[results objectAtIndex:0];
    NSDictionary *row=[table objectAtIndex:0];
    NSData *image_source=[row objectForKey:@"Company_Logo"];
    UIImage *image=[[UIImage alloc] initWithData:image_source];
    image=[UIImage imageWithData:image_source];
    [self.imageView setImage :image];
}
but the final step , it is showing like this, in here
 // [self.imageView setImage :image];
jpegdecompresssurface : picture decode failed : e00002d1
Any one can help me?
Regards.

**Comment by martinrybak** [comment] 2017-01-23 17:05
Duplicate of #40

**Closed by martinrybak** 2017-01-23 17:05 UTC
