### ISSUE TITLE
ipv6 support

### ISSUE THREAD

**Issue by alxsoft** [martinrybak/SQLClient#50] opened 2017-06-06 18:46 UTC
Hello!

I can not connect to database using ipv6 address (which is requirement of Apple now).
<img width="305" alt="screen shot 2017-06-06 at 22 19 51" src="https://user-images.githubusercontent.com/29236870/26846203-0111777e-4b0a-11e7-966a-b2d4f1e90b07.png">

**Comment by martinrybak** [comment] 2017-06-13 14:22
Duplicate of #37. Use the format XXXX:XXXX:X:X::X:XXXX

**Closed by martinrybak** 2017-06-13 14:22 UTC

**Comment by alxsoft** [comment] 2017-06-13 14:33
Hello, Thank you for answer!

Ipv6 is now working correctly.

Looking forward for further development of SQLClient :)

Alexey

**Comment by martinrybak** [comment] 2017-06-13 14:36
I appreciate it! When you have a chance, please test out the `types` branch. Lots of changes in there, including proper data type conversions.

**Comment by alxsoft** [comment] 2017-06-13 14:52
I tried updates branch, had exceptions which I can't understand yet.

Will try types soon.
