### ISSUE TITLE
Image render not complete

### ISSUE THREAD

**Issue by totoourworld** [martinrybak/SQLClient#36] opened 2017-01-07 06:02 UTC
I used type branch's files for SQLClient framework, but used SQLClient.h and m file in master branch.
Because type branch's h&m file is not completed one and issue happened with compiling.
But when i use original h&m file in master branch it is working in compile step.
Also can get the image data but 
"jpegdecompresssurface : picture decode failed" this issue happened and the image is not loading 100%
how can i do this?

**Comment by totoourworld** [comment] 2017-01-20 04:36
Hello, Martin Rybak.
I posted this 13 days ago.
Haven't you got anything to advise me?

**Comment by martinrybak** [comment] 2017-01-23 17:05
Please use SQLClient.h and m from the `types` branch.

**Comment by martinrybak** [comment] 2017-01-24 18:32
Duplicate of #40

**Closed by martinrybak** 2017-01-24 18:32 UTC
